# Generated by Django 5.0 on 2024-01-30 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_department_studentid_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_name']},
        ),
    ]
