# Generated by Django 5.0 on 2024-02-22 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0008_reportrank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportRank',
        ),
    ]
