# Generated by Django 5.0 on 2024-03-16 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0013_user_burger'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=10)),
                ('cardname', models.CharField(max_length=100)),
                ('cardnumber', models.CharField(max_length=16)),
                ('expmonth', models.CharField(max_length=20)),
                ('expyear', models.CharField(max_length=4)),
                ('cvv', models.CharField(max_length=4)),
                ('sameadr', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
        migrations.AddField(
            model_name='burger',
            name='receipe_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='receipe_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='receipe',
            name='receipe_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='receipe_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_burger',
            name='receipe_price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Addcart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vege.user')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vege.product')),
            ],
        ),
        migrations.CreateModel(
            name='User_pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_name', models.CharField(max_length=255)),
                ('receipe_descriptions', models.TextField()),
                ('receipe_image', models.ImageField(upload_to='receipe_images/')),
                ('receipe_price', models.IntegerField(default=0)),
                ('receipe_view_count', models.IntegerField(default=1)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
