# Generated by Django 5.0 on 2024-03-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0014_payment_product_burger_receipe_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addcart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='addcart',
            name='quantity',
        ),
        migrations.AddField(
            model_name='addcart',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='addcart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vege.user'),
        ),
        migrations.CreateModel(
            name='Fooditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipe_descriptions', models.TextField()),
                ('receipe_image', models.ImageField(upload_to='receipe_images/')),
                ('receipe_price', models.IntegerField(default=0)),
                ('receipe_view_count', models.IntegerField(default=1)),
                ('addcart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vege.addcart')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
